security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
    # ...
    access_control:
        - { path: '^/ldap', methods: POST, ips: ['127.0.0.1'] }
        - { path: '^/ldap', roles: ROLE_NO_ACCESS }