monolog:
    # Add new channel to log the synch commands
    channels: ['sync_agent', 'sync_structure', 'sync_ldap']
    
    handlers:
        # Define handler to log in a different file
        sync_agent:
            type: rotating_file
            # default path means templates directory
            # in order to read log into twig render
            path: "%twig.default_path%/sync/%kernel.environment%.sync.agent.log"
            level: debug
            max_files: 10
            channels: ["sync_agent"]
        sync_structure:
            type: rotating_file
            # default path means templates directory
            # in order to read log into twig render
            path: "%twig.default_path%/sync/%kernel.environment%.sync.structure.log"
            level: debug
            max_files: 10
            channels: ["sync_structure"]
        sync_ldap:
            type: rotating_file
            # default path means templates directory
            # in order to read log into twig render
            path: "%twig.default_path%/sync/%kernel.environment%.sync.ldap.log"
            level: debug
            max_files: 10
            channels: ["sync_ldap"]
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            channels: ['!sync_agent', '!sync_structure', '!sync_ldap']
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
