monolog:
    # Add new channel to log the synch commands
    channels: ['sync_agent', 'sync_geisha', 'sync_structure', 'sync_ldap', 'sync_inp', 'api']

    handlers:
        # Define handler to log in a different file
        sync_agent:
            type: rotating_file
            # default path means templates directory
            # in order to read log into twig render
            path: "%twig.default_path%/sync/%kernel.environment%.sync.agent.log"
            level: debug
            max_files: 6
            channels: ["sync_agent"]
        sync_geisha:
            type: rotating_file
            path: "%twig.default_path%/sync/%kernel.environment%.sync.geisha.log"
            level: debug
            max_files: 6
            channels: ["sync_geisha"]
        sync_structure:
            type: rotating_file
            path: "%twig.default_path%/sync/%kernel.environment%.sync.structure.log"
            level: debug
            max_files: 6
            channels: ["sync_structure"]
        sync_ldap:
            type: rotating_file
            path: "%twig.default_path%/sync/%kernel.environment%.sync.ldap.log"
            level: debug
            max_files: 6
            channels: ["sync_ldap"]
        sync_inp:
            type: rotating_file
            path: "%twig.default_path%/sync/%kernel.environment%.sync.inp.log"
            level: debug
            max_files: 6
            channels: ["sync_inp"]
        api:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.api.log"
            level: debug
            channels: ["api"]
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            channels: ['!sync_agent', '!sync_geisha', '!sync_structure', '!sync_ldap', '!sync_inp', '!api']
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ['!sync_agent', '!sync_geisha', '!sync_structure', '!sync_ldap', '!sync_inp', '!api']
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
